//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lua.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to },
        ///            },
        ///        },
        ///    },
        ///}.
        /// </summary>
        internal static string MMDataFooter {
            get {
                return ResourceManager.GetString("MMDataFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} =
        ///{{
        ///    [&quot;Default&quot;] = 
        ///    {{
        ///        [&quot;{1}&quot;] = 
        ///        {{
        ///            [&quot;$AccountWide&quot;] = 
        ///            {{
        ///                [&quot;ItemsConverted&quot;] = true,
        ///                [&quot;version&quot;] = 1,
        ///                [&quot;SalesData&quot;] = 
        ///                {{.
        /// </summary>
        internal static string MMDataHeader {
            get {
                return ResourceManager.GetString("MMDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to },.
        /// </summary>
        internal static string MMDataItemFooter {
            get {
                return ResourceManager.GetString("MMDataItemFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] = 
        ///                    {{.
        /// </summary>
        internal static string MMDataItemHeader {
            get {
                return ResourceManager.GetString("MMDataItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] = 
        ///                                {{
        ///                                    [&quot;seller&quot;] = &quot;{1}&quot;,
        ///                                    [&quot;wasKiosk&quot;] = {2},
        ///                                    [&quot;timestamp&quot;] = {3},
        ///                                    [&quot;itemLink&quot;] = &quot;{4}&quot;,
        ///                                    [&quot;buyer&quot;] = &quot;{5}&quot;,
        ///                                    [&quot;price&quot;] = {6},
        ///                                    [&quot;quant&quot;] = {7},
        ///                                    [&quot;guild&quot;] = &quot;{8}&quot;,
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MMDataSale {
            get {
                return ResourceManager.GetString("MMDataSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }},
        ///                            [&quot;itemIcon&quot;] = &quot;{0}&quot;,
        ///                        }},.
        /// </summary>
        internal static string MMDataSaleFooter {
            get {
                return ResourceManager.GetString("MMDataSaleFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;{0}&quot;] = 
        ///                        {{
        ///                            [&quot;sales&quot;] = 
        ///                            {{.
        /// </summary>
        internal static string MMDataSaleHeader {
            get {
                return ResourceManager.GetString("MMDataSaleHeader", resourceCulture);
            }
        }
    }
}
